server:
  port: 80

spring:
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
      url: jdbc:h2:~/test
      username: sa
      password:
      driver-class-name: org.h2.Driver
      schema: classpath:/db/init.sql
#      # 使用druid数据源
#      type: com.alibaba.druid.pool.DruidDataSource
#      druid:
#        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#        filters: stat,slf4j,config
#        connection-properties: stat.mergeSql=true;stat.slowSqlMillis=5000;
  application:
    name: register-web
  freemarker:
    request-context-attribute: req  #req访问request
    suffix: .ftl  #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置
    template-loader-path: classpath:/META-INF/templates/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
        number_format: '0.##'   #数字格式化，无小数点
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  h2:
    console:
      path: /h2-console
      enabled: true

  resources:
    static-locations: classpath*:/static/**
#  helper-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql
#mapper:
#  not-empty: true
#  mappers: com.reptile.mapper.MyMapper
#  identity: MYSQL
#mybatis:
#  mapper-locations: classpath*:mapper/**/*.xml
#  configuration:
#    map-underscore-to-camel-case: true

#logging:
#  path: logs/
